### ISSUE TITLE
mvn BUILD FAILURE

### ISSUE THREAD

**Issue by sajmmon** [alex-bretet/cloudstreetmarket.com#3]
I cloned your repo on Mac and I can not mvn install it, I get:

Downloaded: https://repo.maven.apache.org/maven2/com/googlecode/flyway/flyway-core/2.3.1/flyway-core-2.3.1.jar (252 KB at 7632.1 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.6/mysql-connector-java-5.1.6.jar (687 KB at 14308.0 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ZipCloud Parent .................................... SUCCESS [  1.359 s]
[INFO] ZipCloud Core ...................................... SUCCESS [ 20.342 s]
[INFO] CloudStreetMarket Parent ........................... FAILURE [  0.618 s]
[INFO] CloudStreetMarket Core ............................. SKIPPED
[INFO] CloudStreetMarket Webapp ........................... SKIPPED
[INFO] CloudStreetMarket API .............................. SKIPPED
[INFO] CloudStreetMarket WebSocket ........................ SKIPPED
[INFO] CloudStreetMarket .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.468 s
[INFO] Finished at: 2017-01-25T16:58:47+00:00
[INFO] Final Memory: 19M/235M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.googlecode.flyway:flyway-maven-plugin:2.3.1:migrate (package) on project cloudstreetmarket-parent: com.googlecode.flyway.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource: Access denied for user ''@'localhost' (using password: NO) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cloudstreetmarket-parent

Thank you

**Comment by alex-bretet** [comment]
Hi Sajmmon,
Sorry for the late reply, I probably missed the notification at the time.
You need to install different third party software at different stages of the book.
Did you install mysql locally prior to starting this build ? 

[wiki page about installation](https://github.com/alex-bretet/cloudstreetmarket.com/wiki/More-installation-instructions)

**Comment by alex-bretet** [comment]
Hi sajmmon,
Sorry for the late reply, I missed the notification I suppose.
I will look into it and let you know.

**Comment by alex-bretet** [comment]
Hi Szymon,

I think you are missing a settings.xml file defined in your .m2 directory as in chapter 9:
https://github.com/alex-bretet/cloudstreetmarket.com/blob/v9.x.x/app/.m2/settings.xml

If you are running the build from master, I have now updated the code to load and migrate an hsql database. The build only won't prepare you a DB locally to run the app. To do so, you will now need to run "mvn clean install -Pcsm_dev". This will migrate a csm database on your local mysql.

If you are running the build from v9.x.x, the code is unchanged and adding the settings.xml file as I told you should fix your problem.

Let me know if you encounter other issues.
Thanks,
Alex
